# Generated by Django 5.2.4 on 2025-07-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان انقضاء'),
        ),
        migrations.AddField(
            model_name='users',
            name='otp',
            field=models.IntegerField(blank=True, null=True, verbose_name='رمز یکبار مصرف'),
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='رمز عبور'),
        ),
    ]
