# Generated by Django 5.2.4 on 2025-07-05 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Azan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('prayer', models.CharField(choices=[('fajr', 'نماز صبح'), ('dhuhr', 'نماز ظهر'), ('asr', 'نماز عصر'), ('maghrib', 'نماز مغرب'), ('isha', 'نماز عشا')], max_length=20, verbose_name='نماز')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تایید شده؟')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اذان',
                'verbose_name_plural': 'اذان ها',
                'db_table': 'azans',
            },
        ),
    ]
