# Generated by Django 5.2.4 on 2025-07-05 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
        ('users', '0002_alter_users_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Takbeer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('prayer', models.CharField(choices=[('fajr', 'نماز صبح'), ('dhuhr', 'نماز ظهر'), ('asr', 'نماز عصر'), ('maghrib', 'نماز مغرب'), ('isha', 'نماز عشا')], max_length=20, verbose_name='نماز')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تایید شده؟')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تکبیر',
                'verbose_name_plural': 'تکبیر ها',
                'db_table': 'takbeers',
            },
        ),
    ]
