# Generated by Django 5.2.4 on 2025-07-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_takbeer'),
    ]

    operations = [
        migrations.AddField(
            model_name='azan',
            name='type',
            field=models.CharField(choices=[('main', 'اصلی'), ('backup', 'ذخیره')], default=1, max_length=20, verbose_name='نوع'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='takbeer',
            name='type',
            field=models.CharField(choices=[('main', 'اصلی'), ('backup', 'ذخیره')], default=1, max_length=20, verbose_name='نوع'),
            preserve_default=False,
        ),
    ]
